### ISSUE TITLE
Small bug: Version info not updated in latest release

### ISSUE THREAD

**Issue by rnjudge** [WojciechMula/pyahocorasick#184] opened 2023-01-20 22:39 UTC
I installed the latest version of pyahocorasick:

```
(ternenv) rose@rose-vm:~/ternenv$ pip install pyahocorasick --no-cache-dir
Collecting pyahocorasick
  Downloading pyahocorasick-2.0.0.tar.gz (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.7/99.7 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyahocorasick
  Building wheel for pyahocorasick (setup.py) ... done
  Created wheel for pyahocorasick: filename=pyahocorasick-2.0.0-cp310-cp310-linux_aarch64.whl size=99431 sha256=95d204b1e1b4d94d4080828c231f668be93702780730bf551b1e0b7191f33c31
  Stored in directory: /tmp/pip-ephem-wheel-cache-xsc5c6xs/wheels/0b/12/77/799db5aeedfa377216de5160c17f5a9a9c8ee2e210cb45d743
Successfully built pyahocorasick
Installing collected packages: pyahocorasick
Successfully installed pyahocorasick-2.0.0
```

However, `pip show` says the version is 1.4.4:
```
(ternenv) rose@rose-vm:~/ternenv$ pip show pyahocorasick
Name: pyahocorasick
Version: 1.4.4
```

**Comment by pombredanne** [comment] 2024-03-21 08:06
Closing as I cannot reproduce:
```
$ pip install pyahocorasick --no-cache-dir
Collecting pyahocorasick
  Downloading pyahocorasick-2.0.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (13 kB)
Downloading pyahocorasick-2.0.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (110 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.8/110.8 kB 2.7 MB/s eta 0:00:00
Installing collected packages: pyahocorasick
Successfully installed pyahocorasick-2.0.0
$ pip show pyahocorasick
Name: pyahocorasick
Version: 2.0.0
...
```
and also:
```
$ pip install pyahocorasick --no-cache-dir --no-binary :all:
Collecting pyahocorasick
  Downloading pyahocorasick-2.0.0.tar.gz (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.7/99.7 kB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyahocorasick
  Building wheel for pyahocorasick (setup.py) ... done
  Created wheel for pyahocorasick: filename=pyahocorasick-2.0.0-cp310-cp310-linux_x86_64.whl size=114267 sha256=4813bfcfcbf31d1f98029a6b3287d380ddb6f5c85dafbb29c680864d7bf6d15c
  Stored in directory: /tmp/pip-ephem-wheel-cache-j8ojpcdf/wheels/d3/e8/70/53e137eaa6bee49040694f938799dcba56f89e7f897b829706
Successfully built pyahocorasick
Installing collected packages: pyahocorasick
Successfully installed pyahocorasick-2.0.0
$ pip show pyahocorasick
Name: pyahocorasick
Version: 2.0.0
```

**Closed by pombredanne** 2024-03-21 08:06 UTC
